-- Minimalne tabele
create table if not exists leads (
  id bigint generated by default as identity primary key,
  club text,
  email text,
  created_at timestamp with time zone default now()
);

create table if not exists offers (
  id bigint generated by default as identity primary key,
  email text not null,
  club text not null,
  content text not null,
  created_at timestamp with time zone default now()
);

create table if not exists reservations (
  id bigint generated by default as identity primary key,
  contractor text not null,
  email text not null,
  date_from date not null,
  date_to date not null,
  seats integer not null,
  rooms text,
  created_at timestamp with time zone default now()
);
